## A (very) short Julia intro

The code is written in [Julia](http://julialang.org).

[Here is a tutorial](https://datatofish.com/add-julia-to-jupyter/) on getting up and running with it.

I will use Julia for my demos. But if there is not a direct translation to Matlab or Python, I will try to provide sample code in the other languages.

The syntax for Julia is very similar to Matlab and Python.  There are some important differences.  By default, Julia does not copy array when it is a function input:

<em>In Julia, all arguments to functions are passed by reference. Some technical computing languages pass arrays by value, and this is convenient in many cases. In Julia, modifications made to input arrays within a function will be visible in the parent function. The entire Julia array library ensures that inputs are not modified by library functions. User code, if it needs to exhibit similar behaviour, should take care to create a copy of inputs that it may modify.</em>

This saves significant memory but it can easily cause unexpected behavior.

In [1]:
function test_fun!(A)
    A[1,1] = 2*A[1,1]
    return A
end

test_fun! (generic function with 1 method)

In [2]:
A = [1 2 3; 4 5 6] # Integer array

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [3]:
test_fun!(A)

2×3 Matrix{Int64}:
 2  2  3
 4  5  6

In [4]:
A # A has changed

2×3 Matrix{Int64}:
 2  2  3
 4  5  6

In [5]:
A = [1 2 3; 4 5 6] # Integer array
function test_fun2(A)
    A = 2*A
    return A
end
test_fun2(A)

2×3 Matrix{Int64}:
 2   4   6
 8  10  12

In [6]:
A # A has not changed

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [7]:
A = [1 2 3; 4 5 6] # Integer array
function test_fun3!(A)
    A[:,1] = 2*A[:,1]
    return A
end
test_fun3!(A)

2×3 Matrix{Int64}:
 2  2  3
 8  5  6

In [8]:
A # A has changed

2×3 Matrix{Int64}:
 2  2  3
 8  5  6

In [9]:
A = [1 2 3; 4 5 6] # Integer array
function test_fun4!(A)
    A[:,:] = 2*A[:,:]
    return A
end
test_fun4!(A)

2×3 Matrix{Int64}:
 2   4   6
 8  10  12

In [10]:
A # A has changed

2×3 Matrix{Int64}:
 2   4   6
 8  10  12

In [ ]:
A = [1 2 3; 4 5 6] # Integer array
function test_fun5!(A)
    A[:,:] *= 2
    return A
end
test_fun5!(A)

In [11]:
A # A has changed

2×3 Matrix{Int64}:
 2   4   6
 8  10  12

Also, where Matlab has the `./` and `.*` operations, Julia has `./`,`.*`,`.-` and `.+` and the same for functions like absolute value: `abs(x)` for a scalar and `abs.(x)` for a vector or array.

Julia also allows for you to use Greek characters:

In [12]:
α = 1.

1.0

In [ ]:
β₁

To get the character type `\alpha` and hit "tab".

Julia is also very particular about types.  For example, Matlab would have no issue with `zeros(10.0,10.0)` and would create a 10 x 10 matrix.  Julia will throw an error.

In [20]:
ones(10,10) + 2

LoadError: MethodError: no method matching +(::Matrix{Float64}, ::Int64)
For element-wise addition, use broadcasting with dot syntax: array .+ scalar
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:591
  +(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:87
  +(::Base.TwicePrecision, ::Number) at twiceprecision.jl:290
  ...

In [16]:
f = x -> sin(x)

#1 (generic function with 1 method)

In [17]:
f(12)

-0.5365729180004349